require 'active_support'
require 'active_support/all'
require 'fnv'

require 'dealer/configuration'
require 'dealer/response'
require 'dealer/request'
require 'dealer/parser'
require 'dealer/serializer'
require 'dealer/operation'

require 'dealer/resources/base'

# Errors
require 'dealer/resources/error'
require 'dealer/resources/forbidden_error'
require 'dealer/resources/attribute_error'
require 'dealer/resources/missing_parameter_error'
require 'dealer/resources/malformed_parameter_error'
require 'dealer/resources/not_found_error'

# Resources
require 'dealer/resources/product'
require 'dealer/resources/artifact_product'
require 'dealer/resources/bundle_product'
require 'dealer/resources/coupon'
require 'dealer/resources/customer'
require 'dealer/resources/customer_product'
require 'dealer/resources/offer'
require 'dealer/resources/transaction'
require 'dealer/resources/stripe_transaction'
require 'dealer/resources/dispute_closed_transaction'
require 'dealer/resources/dispute_created_transaction'
require 'dealer/resources/dispute_funds_reinstated_transaction'
require 'dealer/resources/dispute_funds_withdrawn_transaction'
require 'dealer/resources/dispute_updated_transaction'
require 'dealer/resources/failed_purchase_transaction'
require 'dealer/resources/fixed_discount_coupon'
require 'dealer/resources/free_purchase_transaction'
require 'dealer/resources/paypal_failed_purchase_transaction'
require 'dealer/resources/paypal_pending_purchase_transaction'
require 'dealer/resources/paypal_purchase_transaction'
require 'dealer/resources/paypal_refund_transaction'
require 'dealer/resources/percent_discount_coupon'
require 'dealer/resources/purchase_cancellation_transaction'
require 'dealer/resources/purchase_transaction'
require 'dealer/resources/refund_transaction'
require 'dealer/resources/stripe_dispute_closed_transaction'
require 'dealer/resources/stripe_dispute_created_transaction'
require 'dealer/resources/stripe_dispute_funds_reinstated_transaction'
require 'dealer/resources/stripe_dispute_funds_withdrawn_transaction'
require 'dealer/resources/stripe_dispute_updated_transaction'
require 'dealer/resources/stripe_failed_purchase_transaction'
require 'dealer/resources/stripe_purchase_cancellation_transaction'
require 'dealer/resources/stripe_purchase_transaction'
require 'dealer/resources/stripe_refund_transaction'

